export const set_data = 'set_data'
export const set_detail = 'set_detail'
export const set_total = 'set_total'
export const set_count = 'set_count'
export const concat_to_cart = 'concat_to_cart'
export const set_cart = 'set_cart'
export const antotal = 'antotal'
export const set_incre ='set_incre'